### ISSUE TITLE
Docker exit status 137

### ISSUE THREAD

**Issue by cflorean** [eQTL-Catalogue/rnaseq#6]
Firstly, thanks for the great resource :)

We are trying to run this pipeline on 96 samples. Using command line 

`nextflow run ./rna-seq/main.nf --readPathsFile ./data-manifest.tsv -profile docker -resume`

This is the error message:

Error executing process > 'align_reads:hisat2Align (sampleID)’

Caused by:
Process `align_reads:hisat2Align (sampleID)` terminated with an error exit status (137)
Command executed:

  hisat2 -x Homo_sapiens.GRCh38.dna.primary_assembly.hisat2_index \
          -1 sampleID_1.fq.gz file \
          -2 sampleID_2.fq.gz file \
           \
          --known-splicesite-infile Homo_sapiens.GRCh38.105.hisat2_splice_sites.txt \
          --no-mixed \
          --no-discordant \
          -p 1 \
          --met-stderr \
          --new-summary \
          --summary-file sampleID.hisat2_summary.txt --rg-id sampleID rg CN:wsi \
          | samtools view -bS -F 4 -F 8 -F 256 - > sampleID.bam

Command exit status:
  137

Command output:
  (empty)

Command error:
  Killed
  (ERR): hisat2-align exited with value 137

Work dir:
  /work/68/c1ac6e9bddb04e914b7641cea420d6

When we go into the work directory and execute `bash .command.run` then the alignment will complete. We then use the -resume flag on Nextflow to continue. This is unsustainable though of course.

The same thing happened with the quant_txrev:salmonQuant:makeSalmonIndex (txrevise.grp_1.upstream) step. Error message below:

[e0/3bb949] process > quant_txrev:salmonQuant:makeSalmonIndex (txrevise.grp_1.upstream) [ 16%] 1 of 6, failed: 1
[- ] process > quant_txrev:salmonQuant:salmon_quant -
[- ] process > quant_txrev:salmonQuant:salmon_merge -
[- ] process > quant_leafcutter:bam_to_junc -
[- ] process > quant_leafcutter:cluster_introns -
[- ] process > sample_correlation -
Error executing process > 'quant_txrev:salmonQuant:makeSalmonIndex (txrevise.grp_1.upstream)'

Caused by:
Process quant_txrev:salmonQuant:makeSalmonIndex (txrevise.grp_1.upstream) terminated with an error exit status (137)

Command executed:

salmon index -t txrevise.grp_1.upstream.fa -i txrevise.grp_1.upstream.index

Command exit status:
137

To work around this, we went into the work directory and bash .command.run worked (like above). So it doesn't appear to be specific to the hisat2 process.

We have edited the base.config and the nextflow.config and increased the max memory to 128G for this step, and the max default memory to be 100G.

Has anyone else been having this error with nextflow/docker?

Thanks in advance :)

**Comment by kerimoff** [comment]
Hello,

From my perspective it does not like a docker/nextflow problem. Error code 137 means there is memory related problem. Can you please provide me with `.command.run` file (it is next to .command.run file you tried to run)

My first suspicion is that for some reason it does not use the base.config file and trying to use less memory than expected and fail because of insufficient memory. But it will be clearer when you provide the file I mentioned above

Update:
I checked the configuration file and found out that, indeed, we were not including base.config in `docker` profile. Now I updated the code which should in principle solve this problem if it is what I think it is. So, please pull the latest version and try again :)

Please, feedback about the result.

**Comment by cflorean** [comment]
Thanks for the response :) 

I've pulled the latest version and the 137 error still occurs.

I've attached the .command.run and the .command.err

[command.err.txt](https://github.com/eQTL-Catalogue/rnaseq/files/8916420/command.err.txt)
[command.run.txt](https://github.com/eQTL-Catalogue/rnaseq/files/8916421/command.run.txt)

**Comment by kerimoff** [comment]
I am sorry to hear that, and sorry for replying late, it is kinda busy times. 

Unfortunately, I currently am not able to recognise the reason of this problem. Can you try to run it from within the project directory e.g. 
```
cd ./rna-seq
nextflow run main.nf --readPathsFile ./data-manifest.tsv -profile docker -resume
```

And please add an this code `echo ${task.memory}` to "align_reads:hisat2Align" process like below so that we can see how much memory it is trying to use when it fails:

```
process hisat2Align {
    tag "$samplename"
    publishDir "${params.outdir}/HISAT2/logs/", mode: 'copy', pattern: "*.hisat2_summary.txt", enabled: params.saveInfoLogs
    publishDir "${params.outdir}/HISAT2/aligned/", mode: 'copy', pattern: "*.bam", enabled: params.saveAlignedIntermediates
    container = 'quay.io/eqtlcatalogue/rnaseq_hisat2:v22.03.01'

    input:
    tuple val(samplename), file(reads) 
    path hs2_indices
    path alignment_splicesites

    output:
    path "${samplename}.bam", emit: hisat2_bam_ch
    path "${samplename}.hisat2_summary.txt"

    script:
    index_base = hs2_indices[0].toString() - ~/.\d.ht2/
    seqCenter = params.seqCenter ? "--rg-id ${samplename} --rg CN:${params.seqCenter.replaceAll('\\s','_')}" : ''
    def rnastrandness = ''
    if (forward_stranded && !unstranded){
        rnastrandness = params.singleEnd ? '--rna-strandness F' : '--rna-strandness FR'
    } else if (reverse_stranded && !unstranded){
        rnastrandness = params.singleEnd ? '--rna-strandness R' : '--rna-strandness RF'
    }
    if (params.singleEnd) {
        """
        echo ${task.memory}
        hisat2 -x $index_base \\
                -U $reads \\
                $rnastrandness \\
                --known-splicesite-infile $alignment_splicesites \\
                -p ${task.cpus} \\
                --met-stderr \\
                --new-summary \\
                --summary-file ${samplename}.hisat2_summary.txt $seqCenter \\
                | samtools view -bS -F 4 -F 256 - > ${samplename}.bam
        """
    } else {
        """
        echo ${task.memory}
        hisat2 -x $index_base \\
                -1 ${reads[0]} \\
                -2 ${reads[1]} \\
                $rnastrandness \\
                --known-splicesite-infile $alignment_splicesites \\
                --no-mixed \\
                --no-discordant \\
                -p ${task.cpus} \\
                --met-stderr \\
                --new-summary \\
                --summary-file ${samplename}.hisat2_summary.txt $seqCenter \\
                | samtools view -bS -F 4 -F 8 -F 256 - > ${samplename}.bam
        """
    }
}
```

and if it fails again please share the all `.command.*` files so that I can try to identify the problem.

In a worst case scenario we can have a short zoom call if you like to identify the problem ;)

**Comment by kerimoff** [comment]
Hey @cflorean ,
I think now I may have fixed the problem. 

Please try to pull the latest version and retry. 
Hopefully it will be working.
